name: ${project.name}
main: lootcrate.LootCrate
version: ${project.version}
description: ${project.description}
softdepend: [DecentHolograms, HolographicDisplays, FancyHolograms]
author: A_Brave_Panda
api-version: 1.13
commands:
  lootcrate:
    aliases: [crate, crates, loot]
  meta:
  message:
